@ASPNETTweeter_HostAddress = https://localhost:7235

###

GET {{ASPNETTweeter_HostAddress}}/tweet
Accept: application/json

###

POST {{ASPNETTweeter_HostAddress}}/tweet
Content-Type: application/json

{
    "content": "Hello World!"
}

###

POST {{ASPNETTweeter_HostAddress}}/tweet
Content-Type: application/json

{
    "content": "I love .NET! ❤️"
}

###

PUT {{ASPNETTweeter_HostAddress}}/tweet/66b66193786b480c39e899e7

###

DELETE {{ASPNETTweeter_HostAddress}}/tweet/66b66193786b480c39e899e7

### TODO: Add some tests for error handling