@ASPNETTweeter_HostAddress = https://localhost:7235

###

GET {{ASPNETTweeter_HostAddress}}/tweet
Accept: application/json

###

POST {{ASPNETTweeter_HostAddress}}/tweet
Content-Type: application/json

{
    "content": "Hello World!"
}

###